### ISSUE TITLE
[oauth2] client_secret being actively leaked on unauth'd requests

### ISSUE THREAD

**Issue by katanacrimson** [Heello/heello-php#3]
https://github.com/Heello/heello-php/blob/master/includes/Request.php#L70

On unauth'd requests, the client_secret value is being unnecessarily sent to the server as _GET['secret'], creating additional unwarranted exposure of the client_secret value.  Any logging of GET requests between client application and API will result in disclosure of both of the `client_id` and `client_secret` values.

**Comment by katanacrimson** [comment]
Bump.

**Comment by katanacrimson** [comment]
This is a month old and a potential security problem. Why hasn't this been even addressed?

**Comment by katanacrimson** [comment]
Issue approaching two months in age now.

**Comment by caseym** [comment]
will have this fixed shortly. it's on my radar.

**Comment by caseym** [comment]
Fixed.
